name: CI/CD - Flash Studio to AKS

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  IMAGE_NAME: flashstudio/monolith

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # ---- Guardrails: fail fast if any secret missing ----
    - name: Validate required secrets
      run: |
        test -n "${{ secrets.AZURE_CREDENTIALS }}" || (echo "AZURE_CREDENTIALS missing" && exit 1)
        test -n "${{ secrets.ACR_LOGIN_SERVER }}"  || (echo "ACR_LOGIN_SERVER missing" && exit 1)
        test -n "${{ secrets.RESOURCE_GROUP }}"    || (echo "RESOURCE_GROUP missing" && exit 1)
        test -n "${{ secrets.AKS_CLUSTER_NAME }}"  || (echo "AKS_CLUSTER_NAME missing" && exit 1)
        test -n "${{ secrets.NAMESPACE }}"         || (echo "NAMESPACE missing" && exit 1)

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # ---- Show which subscription/tenant we are in (debug) ----
    - name: Show Azure context
      run: |
        az account show -o table
        echo "ACR_LOGIN_SERVER=${{ secrets.ACR_LOGIN_SERVER }}"
        echo "RG=${{ secrets.RESOURCE_GROUP }}  AKS=${{ secrets.AKS_CLUSTER_NAME }}  NS=${{ secrets.NAMESPACE }}"

    # ---- Login to ACR using Azure session (no username/password needed) ----
    - name: ACR login (via Azure)
      run: |
        ACR_NAME=$(echo "${{ secrets.ACR_LOGIN_SERVER }}" | cut -d. -f1)
        echo "Logging into ACR: $ACR_NAME"
        az acr login -n "$ACR_NAME"
        az acr show -n "$ACR_NAME" -o table

    - name: Build & push image to ACR
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}
        echo "Will build tag: $IMAGE_TAG"
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG .
        docker push  ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Set AKS context
      uses: azure/aks-set-context@v4
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

    # Ensure namespace and basic secrets exist
    - name: Setup namespace and secrets
      run: |
        # Create namespace if it doesn't exist
        kubectl get ns ${{ secrets.NAMESPACE }} >/dev/null 2>&1 || \
        kubectl create ns ${{ secrets.NAMESPACE }}
        
        # Create basic secrets if they don't exist (GitHub Actions will skip if they already exist)
        kubectl create secret generic flashstudio-secrets \
          --from-literal=DATABASE_URL="sqlite:///filmcompany.db" \
          --from-literal=SECRET_KEY="$(openssl rand -base64 32)" \
          --namespace=${{ secrets.NAMESPACE }} \
          --dry-run=client -o yaml | kubectl apply -f -
        
        kubectl create secret generic stripe-secrets \
          --from-literal=STRIPE_PUBLISHABLE_KEY="pk_test_replace_with_your_key" \
          --from-literal=STRIPE_SECRET_KEY="sk_test_replace_with_your_key" \
          --from-literal=STRIPE_WEBHOOK_SECRET="whsec_replace_with_your_secret" \
          --namespace=${{ secrets.NAMESPACE }} \
          --dry-run=client -o yaml | kubectl apply -f -
        
        kubectl create secret generic google-drive-secrets \
          --from-literal=GOOGLE_DRIVE_CREDENTIALS_JSON='{"type":"service_account","project_id":"replace-me"}' \
          --from-literal=GOOGLE_DRIVE_FOLDER_ID="replace_with_folder_id" \
          --namespace=${{ secrets.NAMESPACE }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to AKS
      run: |
        echo "Deploying image: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG"
        
        # Check if deployment exists, if not create it
        if ! kubectl get deployment flashstudio-monolith -n ${{ secrets.NAMESPACE }} >/dev/null 2>&1; then
          echo "Deployment doesn't exist, creating initial deployment..."
          kubectl apply -f k8-deploy/deployment.yaml
          kubectl apply -f k8-deploy/service.yaml
        else
          echo "Deployment exists, updating image..."
        fi
        
        # Update the image
        kubectl -n ${{ secrets.NAMESPACE }} set image deployment/flashstudio-monolith \
          web=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG
        
        # Wait for rollout to complete
        kubectl -n ${{ secrets.NAMESPACE }} rollout status deployment/flashstudio-monolith --timeout=300s
        
        # Show final status
        kubectl get pods -n ${{ secrets.NAMESPACE }}
        kubectl get services -n ${{ secrets.NAMESPACE }}
